version: '3.8'
services:
  mongo:
    image: mongo:3
    restart: always
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://mongo:27017/
volumes:
  mongo-data:
